Implement new login tests
mozilla-iam/rp_login_tests pull request #6
Opened 2017-08-17 11:46 UTC by viorelaioia

2017-09-21 14:20 UTC, johngian requested changes

2017-09-21 14:20 UTC, johngian commented on tests/test_login_to_rps.py
> +    def test_login_biztera(self, selenium, ldap, urls, counter_api):
All three following methods are doing the same thing. Please deduplicate the code and override appropriately.

2017-09-21 14:20 UTC, johngian commented on pages/selfservice_mig.py
> +    def login_with_ldap(self, email, password):
``login_with_ldap`` and ``__init__`` are exactly the same in both classes defined.

2017-09-21 14:20 UTC, johngian commented on pages/testrp.py
> +    def __init__(self, selenium, url):
Same here

2017-09-21 14:20 UTC, johngian commented on pages/testrp.py
> +    def login_with_ldap(self, email, password):
Same here.

2017-09-25 12:32 UTC, viorelaioia commented
@johngian , PR is updated. Can you take another look? Thanks!

2017-09-29 10:05 UTC, johngian approved these changes

2017-09-29 10:51 UTC, merged